Update aws.yml

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -18,18 +18,13 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
               
-
-
-
-
-
+      - name: Check docker-compose installation
+        run: |
+          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "if [ ! -f /usr/local/bin/docker-compose ]; then echo 'docker-compose not found. Please install it on the EC2 instance.'; exit 1; fi"
 
       - name: Deploy Docker Compose
         run: |
-
-          cd ~/docker-compose-react-nodejs-mysql-master
-          sudo docker-compose up -d --build
-          EOF
+          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 'cd ~/docker-compose-react-nodejs-mysql-master && sudo docker-compose up -d --build'
         env:
           EC2_HOST: ${{ secrets.EC2_HOST }}
           EC2_USER: ${{ secrets.EC2_USER }}
